
kind: List
apiVersion: v1
metadata:
  resourceVersion: ""
  selfLink: ""
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: master-user-data
    namespace: openshift-machine-api
  type: Opaque
  data:
    userData: {{ settings.masterUserData }}

