apiVersion: v1
items:
- apiVersion: machine.openshift.io/v1beta1
  kind: MachineSet
  metadata:
    creationTimestamp: null
    labels:
      sigs.k8s.io/cluster-api-cluster: {{ settings.clusterName }}
      sigs.k8s.io/cluster-api-machine-role: worker
      sigs.k8s.io/cluster-api-machine-type: worker
    name: {{ settings.clusterName }}-worker-{{ settings.AWSAvailabilityZone }}
    namespace: openshift-machine-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        sigs.k8s.io/cluster-api-cluster: {{ settings.clusterName }}
        sigs.k8s.io/cluster-api-machineset: {{ settings.clusterName }}-worker-{{ settings.AWSAvailabilityZone }}
    template:
      metadata:
        creationTimestamp: null
        labels:
          sigs.k8s.io/cluster-api-cluster: {{ settings.clusterName }}
          sigs.k8s.io/cluster-api-machine-role: worker
          sigs.k8s.io/cluster-api-machine-type: worker
          sigs.k8s.io/cluster-api-machineset: {{ settings.clusterName }}-worker-{{ settings.AWSAvailabilityZone }}
      spec:
        metadata:
          creationTimestamp: null
        providerSpec:
          value:
            ami:
              id: {{ settings.AmiID }}
            apiVersion: awsproviderconfig.openshift.io/v1beta1
            blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
            deviceIndex: 0
            iamInstanceProfile:
              id: {{ settings.clusterName }}-worker-profile
            instanceType: m4.large
            kind: AWSMachineProviderConfig
            metadata:
              creationTimestamp: null
            placement:
              availabilityZone: {{ settings.AWSAvailabilityZone }}
              region: {{ settings.AWSRegion }}
            publicIp: null
            securityGroups:
            - filters:
              - name: tag:Name
                values:
                - {{ settings.clusterName }}_worker_sg
            subnet:
              filters:
              - name: tag:Name
                values:
                - {{ settings.clusterName }}-private-{{ settings.AWSAvailabilityZone }}
            tags:
            - name: openshiftClusterID
              value: {{ settings.clusterID }}
            - name: kubernetes.io/cluster/{{ settings.clusterName }}
              value: owned
            userDataSecret:
              name: worker-user-data
        versions:
          kubelet: ""
  status:
    replicas: 0
- apiVersion: machine.openshift.io/v1beta1
  kind: MachineSet
  metadata:
    creationTimestamp: null
    labels:
      sigs.k8s.io/cluster-api-cluster: {{ settings.clusterName }}
      sigs.k8s.io/cluster-api-machine-role: worker
      sigs.k8s.io/cluster-api-machine-type: worker
    name: {{ settings.clusterName }}-worker-{{ settings.AWSAvailabilityZone }}
    namespace: openshift-machine-api
  spec:
    replicas: 0
    selector:
      matchLabels:
        sigs.k8s.io/cluster-api-cluster: {{ settings.clusterName }}
        sigs.k8s.io/cluster-api-machineset: {{ settings.clusterName }}-worker-{{ settings.AWSAvailabilityZone }}
    template:
      metadata:
        creationTimestamp: null
        labels:
          sigs.k8s.io/cluster-api-cluster: {{ settings.clusterName }}
          sigs.k8s.io/cluster-api-machine-role: worker
          sigs.k8s.io/cluster-api-machine-type: worker
          sigs.k8s.io/cluster-api-machineset: {{ settings.clusterName }}-worker-{{ settings.AWSAvailabilityZone }}
      spec:
        metadata:
          creationTimestamp: null
        providerSpec:
          value:
            ami:
              id: {{ settings.AmiID }}
            apiVersion: awsproviderconfig.openshift.io/v1beta1
            blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
            deviceIndex: 0
            iamInstanceProfile:
              id: {{ settings.clusterName }}-worker-profile
            instanceType: m4.large
            kind: AWSMachineProviderConfig
            metadata:
              creationTimestamp: null
            placement:
              availabilityZone: {{ settings.AWSAvailabilityZone }}
              region: {{ settings.AWSRegion }}
            publicIp: null
            securityGroups:
            - filters:
              - name: tag:Name
                values:
                - {{ settings.clusterName }}_worker_sg
            subnet:
              filters:
              - name: tag:Name
                values:
                - {{ settings.clusterName }}-private-{{ settings.AWSAvailabilityZone }}
            tags:
            - name: openshiftClusterID
              value: {{ settings.clusterID }}
            - name: kubernetes.io/cluster/{{ settings.clusterName }}
              value: owned
            userDataSecret:
              name: worker-user-data
        versions:
          kubelet: ""
  status:
    replicas: 0
kind: List
metadata: {}
