apiVersion: v1
data:
  install-config: |
    apiVersion: v1beta3
    baseDomain: {{ settings.baseDomain }}
    compute:
    - name: worker
      platform: {}
      replicas: 1
    controlPlane:
      name: master
      platform: {}
      replicas: 1
    metadata:
      creationTimestamp: null
      name: {{ settings.clusterName }}
    networking:
      clusterNetworks:
      - cidr: {{ settings.clusterCIDR }}
        hostSubnetLength: {{ settings.hostSubnetLength }}
      machineCIDR: {{ settings.machineCIDR }}
      serviceCIDR: {{ settings.serviceCIDR }}
      type: {{ settings.SDNType}}
    platform:
      aws:
        region: {{ settings.region }}
    pullSecret: '{{ settings.pullSecret }}'
    sshKey: |
      {{ settings.sshKey }}
metadata:
  name: cluster-config-v1
  namespace: kube-system
