apiVersion: config.openshift.io/v1
kind: DNS
metadata:
  creationTimestamp: null
  name: cluster
spec:
  baseDomain: {{ settings.clusterName }}.{{ settings.baseDomain }}
  privateZone:
    tags:
      Name: {{ settings.clusterName }}_int
      kubernetes.io/cluster/{{ settings.clusterName }}: owned
      openshiftClusterID: {{ settings.clusterID }}
  publicZone:
    id: {{ settings.publicZoneID }}
status: {}
