apiVersion: v1beta3
baseDomain: {{ settings.baseDomain }}
compute:
- name: worker
  platform: {}
  replicas: 1
controlPlane:
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: {{ settings.clusterName }}
networking:
  clusterNetworks:
  - cidr: {{ settings.clusterCIDR }}
    hostSubnetLength: {{ settings.clusterSubnetLength }}
  machineCIDR: {{ settings.machineCIDR }}
  serviceCIDR: {{ settings.serviceCIDR }}
  type: {{ settings.SDNType }}
platform:
  libvirt:
    URI: {{ settings.libvirtURI }}
pullSecret: '{{ settings.pullSecret }}'
sshKey: |
  {{ settings.SSHKey }}
