apiVersion: v1
kind: Secret
metadata:
  name: machine-config-server-tls
  namespace: openshift-machine-config-operator
type: Opaque
data:
  tls.crt: {{ settings.MachineTLSCRT }}
  tls.key: {{ settings.MachineTLSKey }}
